<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>gmMobileApp</title>
<?php echo gm_css(
    array(
        "js/350/cssreset/cssreset.css",
        "js/350/cssbase/cssbase.css",
        "js/350/cssfonts/cssfonts.css",
        "js/350/cssbutton/cssbutton.css",
        "js/350/cssgrids/cssgrids.css",
        "js/350/app-transitions-css/app-transitions-css-min.css",
        "css/gmmobileapp.css"
    ),
    $settings['css']['pack'], $settings['css']['minify'], $settings['css']['inline_images']
); ?>
</head>
<body>
    <div id="gm-app-loader" class="loading" style="display:none;">
        <header>
            <h1>Chargement en cours...</h1>
        </header>
        <p class="gm-loader">Chargement</p>
    </div>
    <script>
    document.getElementById('gm-app-loader').style.display = 'block';
    </script>

    <script id="t-home" type="text/x-handlebars-template">
        <header>
            <h1>Gare mobile</h1>
        </header>
        <h2>Gare favorites</h2>
        {{#if stations}}
        <ul class="gm-station-list">
            {{#each stations}}
            <li data-station-code="{{code}}">
                {{> stationview}}           
            </li>
            {{/each}}
        </ul>
        {{/if}}
        <p class="help"{{#if stations.length}} style="display:none;"{{/if}}>Aucune gare favorite</p>

        <h2>Ajouter des gares favorites</h2>
        {{> searchform}}
    </script>

    <script id="t-search" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Recherche "{{search}}"</h1>
        </header>
        <h2>Résultats</h2>
        {{#unless results}}
        <p class="gm-no-result">Aucune gare ne correspond à cette recherche</p>
        {{else}}
        <ul class="gm-station-list">
            {{#each results}}
            <li data-station-code="{{code}}">
                {{> stationview}}           
            </li>
            {{/each}}
        </ul>
        {{/unless}}
        <h2>Autre recherche</h2>
        {{> searchform}}
    </script>

    <script id="t-departures" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Départs de {{station.name}}</h1>
        </header>
        <h2>Départs de {{station.name}}{{#if time}} à partir de {{time}}{{/if}}</h2>
        <p class="gm-toolbar">
            <a href="#/departures/{{station.code}}" class="yui3-button">Actualiser</a>
        </p>
        {{#if trains}}
            <ul class="gm-departures">
                {{#each trains}}
                    {{> trainview}}
                {{/each}}
            </ul>
        {{else}}
            <p class="gm-error">Une erreur s'est produite durant le chargement des horaires de départs.</p>
        {{/if}}
    </script>

    <script id="t-loading" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Chargement en cours...</h1>
        </header>
        <p class="gm-loader">Chargement</p>
    </script>

    <!-- partials -->
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="trainview">
        <li class="{{#if details}}late{{/if}}">
            <div class="yui3-g">
                <div class="yui3-u-5-6 gm-infos">
                    <span class="time">{{time}}</span>
                    {{#if details}}&ndash; <span class="details">{{details}}</span>{{/if}}
                    {{#if platform}} &ndash; <span title="voie" class="info"> {{platform}}</span>{{/if}}
                </div>
                <div class="yui3-u-1-6 gm-num">
                    {{#if type}}{{type}}{{/if}}
                </div>
                <div class="yui3-u-5-6 gm-destination"><strong>{{destination}}</strong></div>
                <div class="yui3-u-1-6 gm-num">
                    {{#if num}}<span title="N°" class="info">{{num}}</span>{{/if}}
                </div>
            </div>
        </li>
    </script>
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="backhome">
    <a href="#/" class="back-home">↰</a>
    </script>
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="stationview">
        <a class="yui3-button gm-bookmark{{#if bookmarked}} bookmarked{{/if}}" href="#" data-station-code="{{code}}">★</a>
        <strong class="gm-name">{{name}}</strong>
    </script>

    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="searchform">
        <section class="gm-search-form">
            <p>
                <input type="text" placeholder="Nom ou partie du nom de la gare" value="{{search}}" id="search-station" />
            </p>
            <p>
                <button class="gm-geosearch yui3-button yui3-button-primary">À proximité</button>
                <button class="gm-search yui3-button yui3-button-primary">Recherche</button>
            </p>
        </section>
    </script>

    <script src="js/350/yui/yui-min.js"></script>
    <script>
    YUI({
        <?php foreach( $settings['yui'] as $k => $s ) echo "$k: $s,\n" ?>
        modules: {
            gmmobileapp: {
                fullpath: "<?php echo gm_js_file( "gmmobileapp.js", 'js/', $settings['js']['minify'], $settings['js']['command'] ) ?>",
                combine: <?php echo $settings['yui']['combine']; ?>,
                root: "/",
                requires: ['app', 'app-transitions', 'handlebars', 'transition', 'io-base', 'json']
            }
        }
    }).use('gmmobileapp', function (Y) {
        var app = new Y.GMMobileApp({
            serverRouting: false,
            viewContainer: '#gmmobile',
            container: '#gmmobile',
            transitions: true,
            actions: {
                search: 'actions/search.php?str={str}',
                timetable: 'actions/timetable.php?code={code}'
                //timetable: 'actions/timetable.json'
            },
            appLoader: '#gm-app-loader'
        });
        app.render().dispatch();
    });
    </script>
    <div id="gmmobile"></div>
    <noscript>Cette application nécessite l'activation de JavaScript.</noscript>

</body>
</html>
