<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>gmMobileApp</title>
<?php echo gm_css(
    array(
        "js/3.5.0/build/cssreset/cssreset.css",
        "js/3.5.0/build/cssbase/cssbase.css",
        "js/3.5.0/build/cssfonts/cssfonts.css",
        "js/3.5.0/build/cssbutton/cssbutton.css",
        "js/3.5.0/build/cssgrids/cssgrids.css",
        "js/3.5.0/build/app-transitions-css/app-transitions-css-min.css",
        "css/gmmobileapp.css"
    ),
    $settings['css']['pack']
); ?>
</head>
<body>
    <script id="t-home" type="text/x-handlebars-template">
        <header>
            <h1>Gare mobile</h1>
        </header>
        <h2>Gare favorites</h2>
        {{#if stations}}
        <ul class="gm-station-list">
            {{#each stations}}
            <li>
                {{> stationview}}           
            </li>
            {{/each}}
        </ul>
        {{/if}}
        <p class="help"{{#if stations.length}} style="display:none;"{{/if}}>Aucune gare favorite</p>

        <h2>Ajouter des gares favorites</h2>
        {{> searchform}}
    </script>

    <script id="t-search" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Recherche "{{search}}"</h1>
        </header>
        <h2>Résultats</h2>
        <ul class="gm-station-list">
            {{#each results}}
            <li>
                {{> stationview}}           
            </li>
            {{/each}}
        </ul>
        <h2>Autre recherche</h2>
        {{> searchform}}
    </script>

    <script id="t-departures" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Départs de {{station.name}}</h1>
        </header>
        <p class="gm-toolbar">
            <a href="#/departures/{{station.code}}" class="yui3-button">Actualiser</button><a href="#/arrivals/{{station.code}}" class="yui3-button">Voir les arrivées &raquo;</a>
        </p>
        <table summary="Prochains départs de {{station.name}}">
            {{> trainviewheader}}
            {{#each trains}}
                {{> trainview}}
            {{/each}}
        </table>
    </script>

    <script id="t-arrivals" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Arrivées à {{station.name}}</h1>
        </header>
        <p class="gm-toolbar">
            <a href="#/arrivals/{{station.code}}" class="yui3-button">↻ Actualiser</button><a href="#/departures/{{station.code}}" class="yui3-button">Voir les départs &raquo;</a>
        </p>
        <table summary="Prochaines arrivées à {{station.name}}">
            {{> trainviewheader}}
            {{#each trains}}
                {{> trainview}}
            {{/each}}
        </table>
    </script>


    <script id="t-loading" type="text/x-handlebars-template">
        <header>
            {{> backhome}}
            <h1>Chargement en cours...</h1>
        </header>
        <p class="gm-loader">Chargement</p>
    </script>

    <!-- partials -->
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="trainview">
        <tr{{#if details}} class="late"{{/if}}>
            <td class="c">{{type}}</td>
            <td>{{destination}}</td>
            <td class="c">{{time}}</td>
            <td class="c">{{platform}}</td>
            <td class="details">{{details}}</td>
        </tr>
    </script>
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="backhome">
    <a href="#/" class="back-home">↰</a>
    </script>
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="trainviewheader">
        <tr>
            <th>Type</th>
            <th>Destination</th>
            <th>Heure</th>
            <th>Voie</th>
            <th>Retard</th>
        </tr>
    </script>
    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="stationview">
        <div class="gm-action">
            <a class="yui3-button" href="#/departures/{{code}}"><abbr title="Départs"><span>Dép.</span></abbr> &raquo;</a>
            <a class="yui3-button" href="#/arrivals/{{code}}"><abbr title="Arrivées"><span>Arr.</span></abbr> &raquo;</a>
        </div>
        <a class="yui3-button gm-bookmark{{#if bookmarked}} bookmarked{{/if}}" href="#" data-station-code="{{code}}">★</a>
        <strong class="gm-name">{{name}}</strong>
    </script>

    <script class="gm-t-partial" type="text/x-handlebars-template" data-name="searchform">
        <section class="gm-search-form">
            <p>
                <input type="text" placeholder="Nom ou partie du nom de la gare" value="{{search}}" id="search-station" />
            </p>
            <p>
                <button class="gm-geosearch yui3-button yui3-button-primary">À proximité</button>
                <button class="gm-search yui3-button yui3-button-primary">Recherche</button>
            </p>
        </section>
    </script>

    <script src="js/3.5.0/build/yui/yui-min.js"></script>
    <script src="js/gmmobileapp.js"></script>
    <script>
    YUI({
<?php foreach( $settings['yui'] as $k => $s ) echo "$k: $s,\n" ?>
    }).use('gmmobileapp', function (Y) {


        var app = new Y.GMMobileApp({
            serverRouting: false,
            viewContainer: '#gmmobile',
            container: '#gmmobile',
            transitions: true,
            actions: {
                search: 'actions/search.php?str={str}'
            }
        });

        app.render().dispatch();
    });
    </script>
    <div id="gmmobile"></div>

</body>
</html>
